name: "Unit Test"
on:
  workflow_call:

env:
  TEST_VAR: 10
  GO_VERSION: 1.23.2

jobs:
  test:
    name: "Unit test linux"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false

      - name: Load Go build cache
        id: go-cache-build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
          key: linux-go-${{ env.GO_VERSION }}-v1-build-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            linux-go-${{ env.GO_VERSION }}-v6-build-

      - name: Install Go modules
        shell: bash
        run: go mod tidy

      - name: Run tests
        shell: bash
        run: go test ./...
